<?php

namespace Database\Seeders;

use App\Models\Semestre;
use App\Models\Unidad;
use App\Models\Pregunta;
use Illuminate\Database\Seeder;

class PreguntasAdicionalesSeeder extends Seeder
{
    public function run(): void
    {
        // Obtener los semestres de Matemáticas CCH
        $semestres = Semestre::all()->keyBy('numero');

        // Definiremos las 15 preguntas adicionales para cada semestre y unidad
        $adicionales = [
            // ================== SEMESTRE 1 ==================
            1 => [
                // U1: Números y operaciones
                1 => [
                    ['texto' => 'Simplifica la expresión con paréntesis y corchetes: \\( 5 - [2 - (8 - 3)] \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '8', 'B' => '0', 'C' => '6', 'D' => '4'], 'correcta' => 'A'],
                    ['texto' => 'Calcula el resultado de la siguiente suma de enteros: \\( -15 + (-7) - (-12) \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-10', 'B' => '-34', 'C' => '10', 'D' => '-20'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el inverso multiplicativo de \\( \\frac{3}{5} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{5}{3} \\)', 'B' => '\\( -\\frac{3}{5} \\)', 'C' => '\\( -\\frac{5}{3} \\)', 'D' => '1'], 'correcta' => 'A'],
                    ['texto' => 'Simplifica la expresión exponencial: \\( (2^3 \\cdot 2^2)^2 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1024', 'B' => '512', 'C' => '256', 'D' => '2048'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve respetando la jerarquía de operaciones: \\( 12 \\div 3 \\cdot 2 + 5 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '13', 'B' => '7', 'C' => '2', 'D' => '11'], 'correcta' => 'A'],
                    ['texto' => 'Representa en lenguaje algebraico: "La suma de tres números enteros consecutivos".', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x + (x+1) + (x+2) \\)', 'B' => '\\( 3x \\)', 'C' => '\\( x + y + z \\)', 'D' => '\\( x^3 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Identifica cuál de las siguientes opciones es un número irracional.', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\pi \\)', 'B' => '0.333...', 'C' => '\\( \\sqrt{4} \\)', 'D' => '\\( -5 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Calcula el resultado de: \\( \\frac{5}{8} \\div \\frac{3}{4} \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{5}{6} \\)', 'B' => '\\( \\frac{15}{32} \\)', 'C' => '\\( \\frac{6}{5} \\)', 'D' => '\\( \\frac{10}{12} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de la expresión \\( |-8 + 3| \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '-5', 'C' => '11', 'D' => '-11'], 'correcta' => 'A'],
                    ['texto' => 'Traduce al lenguaje algebraico: "La tercera parte del cubo de un número".', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{x^3}{3} \\)', 'B' => '\\( 3x^3 \\)', 'C' => '\\( (\\frac{x}{3})^3 \\)', 'D' => '\\( x^3 - 3 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Simplifica la expresión utilizando leyes de exponentes: \\( \\frac{a^{-2} \\cdot a^5}{a^2} \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( a \\)', 'B' => '\\( a^2 \\)', 'C' => '\\( a^5 \\)', 'D' => '\\( a^{-1} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve: \\( 4 \\cdot (3 - 5)^2 - 6 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '10', 'B' => '10', 'C' => '-14', 'D' => '2'], 'correcta' => 'A'],
                    ['texto' => 'Calcula el mínimo común múltiplo (m.c.m.) de 12 y 18.', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '36', 'B' => '6', 'C' => '72', 'D' => '18'], 'correcta' => 'A'],
                    ['texto' => 'Define formalmente en qué consiste la jerarquía de las operaciones y el uso de los signos de agrupación.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'La jerarquía indica el orden para resolver operaciones: primero signos de agrupación (paréntesis, corchetes, llaves), luego potencias y raíces, seguido de multiplicaciones y divisiones de izquierda a derecha, y al final sumas y restas.'],
                    ['texto' => 'Simplifica la expresión aritmética y detalla el procedimiento paso a paso: \\( \\frac{3}{5} \\cdot \\frac{2}{3} + \\frac{1}{10} \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Multiplicación: (3*2)/(5*3) = 6/15 = 2/5. Suma: 2/5 + 1/10 = 4/10 + 1/10 = 5/10 = 1/2.']
                ],
                // U2: Variación lineal
                2 => [
                    ['texto' => 'Encuentra la pendiente de la recta que pasa por los puntos \\( (1, 3) \\) y \\( (4, 9) \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '2', 'B' => '3', 'C' => '-2', 'D' => '\\( \\frac{1}{2} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Identifica la ordenada al origen de la recta con ecuación \\( y = 3x - 5 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-5', 'B' => '3', 'C' => '5', 'D' => '0'], 'correcta' => 'A'],
                    ['texto' => 'Si \\( y \\) varía directamente con \\( x \\), y \\( y = 12 \\) cuando \\( x = 3 \\), ¿cuánto vale \\( y \\) cuando \\( x = 5 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '20', 'B' => '15', 'C' => '10', 'D' => '25'], 'correcta' => 'A'],
                    ['texto' => 'Dada la recta \\( y = -2x + 4 \\), ¿en qué coordenada cruza al eje X?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, 0) \\)', 'B' => '\\( (0, 4) \\)', 'C' => '\\( (-2, 0) \\)', 'D' => '\\( (4, 0) \\)'], 'correcta' => 'A'],
                    ['texto' => 'La pendiente de una recta horizontal es siempre:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Cero', 'B' => 'Indefinida', 'C' => '1', 'D' => '-1'], 'correcta' => 'A'],
                    ['texto' => 'Una recta que sube de izquierda a derecha en el plano cartesiano tiene una pendiente:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Positiva', 'B' => 'Negativa', 'C' => 'Nula', 'D' => 'Infinita'], 'correcta' => 'A'],
                    ['texto' => 'Si un auto viaja a una velocidad constante de 80 km/h, ¿qué ecuación representa la distancia \\( d \\) en función de las horas \\( t \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( d = 80t \\)', 'B' => '\\( d = 80 + t \\)', 'C' => '\\( d = \\frac{80}{t} \\)', 'D' => '\\( d = 80 - t \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de una recta paralela a la recta \\( y = 5x - 2 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '-5', 'C' => '\\( -\\frac{1}{5} \\)', 'D' => '\\( \\frac{1}{5} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de una recta perpendicular a la recta \\( y = -3x + 1 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{1}{3} \\)', 'B' => '3', 'C' => '-3', 'D' => '\\( -\\frac{1}{3} \\)'], 'correcta' => 'A'],
                    ['texto' => 'En la ecuación \\( y = mx + b \\), si \\( m > 0 \\) y \\( b < 0 \\), la recta pasa por los cuadrantes:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'I, III y IV', 'B' => 'I, II y III', 'C' => 'II, III y IV', 'D' => 'I, II y IV'], 'correcta' => 'A'],
                    ['texto' => 'Un plan telefónico cobra $100 fijos al mes más $2 por cada minuto consumido. Expresa el costo total \\( C \\) en función de los minutos \\( m \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( C = 2m + 100 \\)', 'B' => '\\( C = 100m + 2 \\)', 'C' => '\\( C = 2m - 100 \\)', 'D' => '\\( C = 102m \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si una recta pasa por \\( (0, 0) \\) y \\( (2, 4) \\), su ecuación es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = 2x \\)', 'B' => '\\( y = 4x \\)', 'C' => '\\( y = x + 2 \\)', 'D' => '\\( y = \\frac{1}{2}x \\)'], 'correcta' => 'A'],
                    ['texto' => 'El valor de la pendiente de la recta que tiene una inclinación de 45 grados es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1', 'B' => '0', 'C' => '0.5', 'D' => 'Indefinido'], 'correcta' => 'A'],
                    ['texto' => 'Explica con tus palabras la diferencia entre proporcionalidad directa y una relación afín del tipo \\( y = mx + b \\) con \\( b \\neq 0 \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'La proporcionalidad directa pasa por el origen (0,0), de modo que y/x siempre es constante. La relación afín y = mx + b con b diferente de 0 no pasa por el origen; tiene un valor constante inicial b.'],
                    ['texto' => 'Encuentra la ecuación de la recta que pasa por el punto \\( (3, 2) \\) y tiene pendiente \\( m = -2 \\). Muestra tu procedimiento.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Usando y - y1 = m(x - x1): y - 2 = -2(x - 3) => y - 2 = -2x + 6 => y = -2x + 8.']
                ],
                // U3: Ecuaciones lineales
                3 => [
                    ['texto' => 'Resuelve la ecuación lineal: \\( 3x - 5 = 10 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '15', 'C' => '3', 'D' => '-5'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra el valor de \\( x \\) en: \\( 5x + 3 = 2x + 12 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '3', 'B' => '5', 'C' => '9', 'D' => '2'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve: \\( 2(x - 3) = 8 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '7', 'B' => '5', 'C' => '4', 'D' => '10'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra la solución de: \\( \\frac{x}{4} + 1 = 3 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '8', 'B' => '4', 'C' => '12', 'D' => '16'], 'correcta' => 'A'],
                    ['texto' => 'Si al triple de un número le restas 4, obtienes 17. ¿Cuál es el número?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '7', 'B' => '5', 'C' => '6', 'D' => '8'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve para \\( y \\): \\( 4 - y = 9 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-5', 'B' => '5', 'C' => '13', 'D' => '-13'], 'correcta' => 'A'],
                    ['texto' => 'Despeja la variable \\( r \\) de la fórmula del perímetro del círculo: \\( P = 2\\pi r \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( r = \\frac{P}{2\\pi} \\)', 'B' => '\\( r = P - 2\\pi \\)', 'C' => '\\( r = \\frac{2\\pi}{P} \\)', 'D' => '\\( r = 2\\pi P \\)'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve: \\( 3(2x + 1) = 2(x - 2) + 11 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1', 'B' => '2', 'C' => '-1', 'D' => '0'], 'correcta' => 'A'],
                    ['texto' => 'Un padre tiene 40 años y su hijo 10. ¿Dentro de cuántos años la edad del padre será el triple de la del hijo?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5 años', 'B' => '10 años', 'C' => '15 años', 'D' => '8 años'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve la ecuación: \\( \\frac{2x - 3}{5} = 3 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '9', 'B' => '6', 'C' => '18', 'D' => '12'], 'correcta' => 'A'],
                    ['texto' => 'Despeja \\( x \\) en la ecuación de la recta ordinaria: \\( y = mx + b \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = \\frac{y-b}{m} \\)', 'B' => '\\( x = \\frac{y+b}{m} \\)', 'C' => '\\( x = m(y-b) \\)', 'D' => '\\( x = \\frac{m}{y-b} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve la ecuación: \\( 4x - 7 = 4x + 2 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'No tiene solución', 'B' => 'Tiene infinitas soluciones', 'C' => 'x = 0', 'D' => 'x = -9'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra la solución de: \\( \\frac{x}{2} + \\frac{x}{3} = 5 \\)', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '6', 'B' => '5', 'C' => '10', 'D' => '12'], 'correcta' => 'A'],
                    ['texto' => 'Despeja \\( C \\) de la ecuación de conversión de temperatura: \\( F = \\frac{9}{5}C + 32 \\). Muestra tu procedimiento.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'F - 32 = (9/5)C => (5/9)(F - 32) = C => C = (5/9)*(F - 32).'],
                    ['texto' => 'Plantea la ecuación lineal y resuelve el siguiente problema: "La suma de tres números enteros consecutivos es igual a 72. ¿Cuáles son los números?".', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Ecuación: x + (x+1) + (x+2) = 72 => 3x + 3 = 72 => 3x = 69 => x = 23. Los números son 23, 24 y 25.']
                ],
                // U4: Sistemas 2x2
                4 => [
                    ['texto' => 'Resuelve el siguiente sistema por sustitución: \\( x + y = 5 \\) y \\( 2x - y = 4 \\). ¿Cuál es el valor de \\( x \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '3', 'B' => '2', 'C' => '4', 'D' => '1'], 'correcta' => 'A'],
                    ['texto' => 'En el sistema: \\( 3x + 2y = 12 \\) y \\( 3x - 2y = 0 \\). ¿Cuál es el valor de \\( y \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '3', 'B' => '2', 'C' => '4', 'D' => '6'], 'correcta' => 'A'],
                    ['texto' => 'En un corral hay conejos y gallinas. Si se cuentan 15 cabezas y 50 patas, ¿cuántos conejos hay?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '10 conejos', 'B' => '5 conejos', 'C' => '8 conejos', 'D' => '12 conejos'], 'correcta' => 'A'],
                    ['texto' => 'Si dos rectas representadas en un sistema de ecuaciones de 2x2 son paralelas, se dice que el sistema:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'No tiene solución', 'B' => 'Tiene una solución única', 'C' => 'Tiene infinitas soluciones', 'D' => 'Es inconsistente compatible'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve el sistema: \\( y = 2x \\) y \\( x + 2y = 10 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, 4) \\)', 'B' => '\\( (4, 2) \\)', 'C' => '\\( (3, 6) \\)', 'D' => '\\( (1, 2) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si sumamos dos números el resultado es 20 y su diferencia es 4. ¿Cuáles son los números?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '12 y 8', 'B' => '10 y 10', 'C' => '14 y 6', 'D' => '15 y 5'], 'correcta' => 'A'],
                    ['texto' => 'Para eliminar la variable \\( x \\) por suma y resta en: \\( 2x + 3y = 8 \\) y \\( x - 2y = -3 \\), podemos multiplicar la segunda ecuación por:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-2', 'B' => '2', 'C' => '3', 'D' => '-3'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve el sistema: \\( 4x + y = 9 \\) y \\( 3x - y = 5 \\). ¿Cuál es la coordenada de solución?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, 1) \\)', 'B' => '\\( (1, 2) \\)', 'C' => '\\( (2, -1) \\)', 'D' => '\\( (3, -3) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor del determinante principal \\( D \\) del sistema: \\( 2x - y = 5 \\) y \\( x + 3y = 4 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '7', 'B' => '5', 'C' => '-7', 'D' => '6'], 'correcta' => 'A'],
                    ['texto' => 'Dos rectas coincidentes (la misma recta graficada dos veces) representan un sistema con:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Infinitas soluciones', 'B' => 'Sin solución', 'C' => 'Una solución en el origen', 'D' => 'Una solución única'], 'correcta' => 'A'],
                    ['texto' => 'Un boleto de adulto cuesta $50 y uno de niño $30. Si se vendieron 100 boletos y se recaudaron $4,200, ¿cuántos de adulto se vendieron?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '60', 'B' => '40', 'C' => '50', 'D' => '70'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve el sistema de ecuaciones: \\( 5x + 3y = 7 \\) y \\( 3x - y = 7 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, -1) \\)', 'B' => '\\( (1, 2) \\)', 'C' => '\\( (2, 1) \\)', 'D' => '\\( (0, 0) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra el valor de \\( x \\) en el sistema: \\( \\frac{x}{2} + y = 3 \\) y \\( x - y = 3 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '4', 'B' => '2', 'C' => '1', 'D' => '3'], 'correcta' => 'A'],
                    ['texto' => 'Describe las diferencias clave entre los métodos de sustitución y reducción para resolver sistemas de ecuaciones lineales 2x2.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Sustitución consiste en despejar una variable en una ecuación y meterla en la otra. Reducción (suma y resta) multiplica una o ambas ecuaciones por constantes para sumar y cancelar una de las variables directamente.'],
                    ['texto' => 'Plantea el sistema de ecuaciones y resuelve: "Un estudiante pagó $34 por 2 lápices y 3 plumas. Otro estudiante pagó $26 por 3 lápices y 1 pluma. ¿Cuánto cuesta cada lápiz y cada pluma?".', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Sistema: 2x + 3y = 34 y 3x + y = 26. Multiplicando la segunda por -3: -9x - 3y = -78. Sumando: -7x = -44 => lápiz cuesta $6, pluma cuesta $7.']
                ]
            ],
            // ================== SEMESTRE 2 ==================
            2 => [
                // U1: Ecuaciones cuadráticas
                1 => [
                    ['texto' => 'Resuelve la ecuación cuadrática por factorización: \\( x^2 - 5x + 6 = 0 \\). Las raíces son:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = 2, x = 3', 'B' => 'x = -2, x = -3', 'C' => 'x = 1, x = 6', 'D' => 'x = -1, x = 5'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor del discriminante de la ecuación \\( x^2 + 4x + 4 = 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0', 'B' => '16', 'C' => '8', 'D' => '-8'], 'correcta' => 'A'],
                    ['texto' => 'Si el discriminante de una ecuación cuadrática es menor que cero, sus raíces son:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Complejas conjugadas (no reales)', 'B' => 'Reales iguales', 'C' => 'Reales y distintas', 'D' => 'Enteras negativas'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las soluciones de la ecuación incompleta: \\( 3x^2 - 12 = 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = 2, x = -2', 'B' => 'x = 4, x = -4', 'C' => 'x = 2', 'D' => 'No tiene solución real'], 'correcta' => 'A'],
                    ['texto' => '¿Cuáles son las soluciones de la ecuación cuadrática: \\( x^2 - 9 = 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = 3, x = -3', 'B' => 'x = 9, x = -9', 'C' => 'x = 3', 'D' => 'x = 0'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve por la fórmula general: \\( x^2 - 3x - 10 = 0 \\). Las soluciones son:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = 5, x = -2', 'B' => 'x = -5, x = 2', 'C' => 'x = 10, x = -1', 'D' => 'x = 0, x = 3'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la forma factorizada del término cuadrático \\( x^2 + 8x + 15 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (x+3)(x+5) \\)', 'B' => '\\( (x-3)(x-5) \\)', 'C' => '\\( (x+2)(x+6) \\)', 'D' => '\\( (x-1)(x-15) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve la ecuación incompleta mixta: \\( x^2 - 6x = 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = 0, x = 6', 'B' => 'x = 6', 'C' => 'x = 0, x = -6', 'D' => 'x = 2, x = 3'], 'correcta' => 'A'],
                    ['texto' => '¿Qué término completa el trinomio cuadrado perfecto de la expresión \\( x^2 + 10x \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '25', 'B' => '100', 'C' => '50', 'D' => '5'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la fórmula general utilizada para resolver ecuaciones cuadráticas de la forma \\( ax^2 + bx + c = 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\)', 'B' => '\\( x = -b \\pm \\frac{\\sqrt{b^2 - 4ac}}{2a} \\)', 'C' => '\\( x = \\frac{-b \\pm \\sqrt{b^2 + 4ac}}{2a} \\)', 'D' => '\\( x = \\frac{b \\pm \\sqrt{b^2 - 4ac}}{2a} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve: \\( 2x^2 + 5x - 3 = 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = 1/2, x = -3', 'B' => 'x = -1/2, x = 3', 'C' => 'x = 1, x = -3', 'D' => 'x = 2, x = -3'], 'correcta' => 'A'],
                    ['texto' => 'El área de un rectángulo es 24 cm². Si su largo mide 2 cm más que su ancho, ¿cuáles son sus dimensiones?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '6 cm y 4 cm', 'B' => '8 cm y 3 cm', 'C' => '12 cm y 2 cm', 'D' => '6 cm y 8 cm'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las soluciones de la ecuación cuadrática: \\( x^2 + 6x + 9 = 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'x = -3', 'B' => 'x = 3', 'C' => 'x = 3, x = -3', 'D' => 'x = 0'], 'correcta' => 'A'],
                    ['texto' => 'Explica la relación entre el signo del discriminante y el tipo de soluciones que posee una ecuación cuadrática.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Si el discriminante es positivo, hay dos soluciones reales y distintas. Si es cero, hay una única solución real (soluciones reales iguales). Si es negativo, no hay soluciones reales, sino dos soluciones complejas conjugadas.'],
                    ['texto' => 'Resuelve la ecuación cuadrática utilizando el método de completar el trinomio cuadrado perfecto: \\( x^2 + 6x - 7 = 0 \\). Detalla los pasos.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'x^2 + 6x = 7 => Sumar (6/2)^2 = 9 a ambos lados => x^2 + 6x + 9 = 16 => (x + 3)^2 = 16 => x + 3 = +/- 4 => raíces: x = 1, x = -7.']
                ],
                // U2: Funciones cuadráticas
                2 => [
                    ['texto' => '¿Cuál es la coordenada del vértice de la parábola representada por la función cuadrática \\( y = (x - 3)^2 + 2 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (3, 2) \\)', 'B' => '\\( (-3, 2) \\)', 'C' => '\\( (3, -2) \\)', 'D' => '\\( (2, 3) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si el coeficiente \\( a \\) de la función cuadrática \\( y = ax^2 + bx + c \\) es negativo, la parábola abre hacia:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Abajo', 'B' => 'Arriba', 'C' => 'La derecha', 'D' => 'La izquierda'], 'correcta' => 'A'],
                    ['texto' => 'El vértice de la parábola \\( y = x^2 - 4x + 7 \\) se localiza en el punto:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, 3) \\)', 'B' => '\\( (-2, 19) \\)', 'C' => '\\( (2, 7) \\)', 'D' => '\\( (4, 7) \\)'], 'correcta' => 'A'],
                    ['texto' => 'El eje de simetría de la parábola \\( y = 2(x + 1)^2 - 5 \\) es la recta:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = -1 \\)', 'B' => '\\( x = 1 \\)', 'C' => '\\( y = -5 \\)', 'D' => '\\( x = 2 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor máximo o mínimo de la función cuadrática \\( f(x) = -(x - 4)^2 + 9 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Máximo de 9', 'B' => 'Mínimo de 9', 'C' => 'Máximo de 4', 'D' => 'Mínimo de 4'], 'correcta' => 'A'],
                    ['texto' => '¿En qué punto cruza al eje Y la gráfica de la función cuadrática \\( y = 2x^2 - 3x - 5 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (0, -5) \\)', 'B' => '\\( (0, 2) \\)', 'C' => '\\( (0, -3) \\)', 'D' => '\\( (5, 0) \\)'], 'correcta' => 'A'],
                    ['texto' => 'El discriminante de la parábola \\( y = x^2 - 2x + 5 \\) es menor que cero. Esto significa que la gráfica:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'No cruza al eje X', 'B' => 'Cruza al eje X en dos puntos', 'C' => 'Es tangente al eje X', 'D' => 'No cruza al eje Y'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las coordenadas de las intersecciones con el eje X de la parábola \\( y = x^2 - 4 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, 0) \\) y \\( (-2, 0) \\)', 'B' => '\\( (4, 0) \\) y \\( (-4, 0) \\)', 'C' => '\\( (0, 2) \\) y \\( (0, -2) \\)', 'D' => '\\( (2, -2) \\)'], 'correcta' => 'A'],
                    ['texto' => 'La coordenada X del vértice de la parábola \\( y = ax^2 + bx + c \\) se calcula mediante la fórmula:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = -\\frac{b}{2a} \\)', 'B' => '\\( x = \\frac{b}{2a} \\)', 'C' => '\\( x = -\\frac{2b}{a} \\)', 'D' => '\\( x = -\\frac{c}{2a} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si una parábola tiene vértice en \\( (1, -4) \\) y abre hacia arriba, el rango o contradominio de la función es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( [ -4, \\infty ) \\)', 'B' => '\\( ( -\\infty, -4 ] \\)', 'C' => '\\( [ 1, \\infty ) \\)', 'D' => 'Todos los reales'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál de las siguientes es una función cuadrática ordinaria expresada en su forma canónica?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = a(x - h)^2 + k \\)', 'B' => '\\( y = ax^2 + bx + c \\)', 'C' => '\\( y = a(x - x1)(x - x2) \\)', 'D' => '\\( y = mx + b \\)'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra el vértice de la parábola: \\( y = -x^2 + 6x - 5 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (3, 4) \\)', 'B' => '\\( (-3, -32) \\)', 'C' => '\\( (3, -14) \\)', 'D' => '\\( (0, -5) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si el vértice de una parábola es \\( (0, 0) \\) y pasa por el punto \\( (2, 8) \\), ¿cuál es su ecuación?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = 2x^2 \\)', 'B' => '\\( y = 4x^2 \\)', 'C' => '\\( y = x^2 \\)', 'D' => '\\( y = 8x^2 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Un proyectil sigue una trayectoria dada por la función cuadrática \\( h(t) = -5t^2 + 20t + 10 \\). ¿En qué tiempo \\( t \\) alcanza su altura máxima y cuál es dicho valor?', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Tiempo: t = -b/(2a) = -20/(2*-5) = 2 segundos. Altura máxima: h(2) = -5(2)^2 + 20(2) + 10 = -20 + 40 + 10 = 30 metros.'],
                    ['texto' => 'Explica detalladamente la influencia del coeficiente \\( a \\) en la amplitud y la dirección de apertura de la parábola \\( y = ax^2 + bx + c \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Si a > 0 abre hacia arriba; si a < 0 abre hacia abajo. Su magnitud determina la amplitud: si |a| > 1 la parábola es más estrecha (estiramiento vertical); si 0 < |a| < 1 es más ancha (compresión vertical).']
                ],
                // U3: Geometría plana
                3 => [
                    ['texto' => '¿Cuál es la suma de los ángulos interiores de cualquier triángulo plano?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '180°', 'B' => '360°', 'C' => '90°', 'D' => '270°'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la fórmula para calcular la suma de los ángulos interiores de un polígono regular de \\( n \\) lados?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 180°(n - 2) \\)', 'B' => '\\( 360°(n - 2) \\)', 'C' => '\\( 180°n \\)', 'D' => '\\( \\frac{180°(n - 2)}{n} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Determina el área de un triángulo equilátero que tiene un perímetro de 30 cm.', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 25\\sqrt{3} \\text{ cm}^2 \\)', 'B' => '50 cm²', 'C' => '\\( 10\\sqrt{3} \\text{ cm}^2 \\)', 'D' => '25 cm²'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la medida de cada ángulo interior de un hexágono regular?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '120°', 'B' => '108°', 'C' => '135°', 'D' => '90°'], 'correcta' => 'A'],
                    ['texto' => 'El área de un círculo de radio \\( r = 5 \\text{ cm} \\) expresada en términos de pi es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 25\\pi \\text{ cm}^2 \\)', 'B' => '\\( 10\\pi \\text{ cm}^2 \\)', 'C' => '\\( 5\\pi \\text{ cm}^2 \\)', 'D' => '\\( 50\\pi \\text{ cm}^2 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si la base de un rectángulo mide 8 cm y su altura 5 cm, su perímetro mide:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '26 cm', 'B' => '40 cm', 'C' => '13 cm', 'D' => '20 cm'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor del ángulo complementario de un ángulo de 35°?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '55°', 'B' => '145°', 'C' => '65°', 'D' => '45°'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor del ángulo suplementario de un ángulo de 120°?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '60°', 'B' => '30°', 'C' => '90°', 'D' => '180°'], 'correcta' => 'A'],
                    ['texto' => 'Un trapecio tiene bases de 10 cm y 6 cm, y una altura de 4 cm. Su área es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '32 cm²', 'B' => '16 cm²', 'C' => '24 cm²', 'D' => '64 cm²'], 'correcta' => 'A'],
                    ['texto' => '¿Cómo se definen físicamente dos rectas secantes perpendiculares?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Se intersectan formando ángulos de 90°', 'B' => 'Nunca se tocan en el plano', 'C' => 'Se intersectan en cualquier ángulo', 'D' => 'Tienen la misma pendiente'], 'correcta' => 'A'],
                    ['texto' => 'El perímetro de un cuadrado que tiene un área de 81 cm² es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '36 cm', 'B' => '9 cm', 'C' => '18 cm', 'D' => '81 cm'], 'correcta' => 'A'],
                    ['texto' => '¿Cuántos grados suman los ángulos interiores de un pentágono regular?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '540°', 'B' => '360°', 'C' => '720°', 'D' => '180°'], 'correcta' => 'A'],
                    ['texto' => 'El área de un rombo cuyas diagonales miden 12 cm y 8 cm es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '48 cm²', 'B' => '96 cm²', 'C' => '24 cm²', 'D' => '12 cm²'], 'correcta' => 'A'],
                    ['texto' => 'Demuestra y calcula la medida de los ángulos de un triángulo si están en una relación de 2:3:4.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Ecuación: 2x + 3x + 4x = 180° => 9x = 180° => x = 20°. Los ángulos miden: 2(20)=40°, 3(20)=60° y 4(20)=80°.'],
                    ['texto' => 'Encuentra el área y perímetro de un triángulo rectángulo cuyos catetos miden 6 cm y 8 cm.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Hipotenusa = raíz(6^2 + 8^2) = 10 cm. Perímetro = 6 + 8 + 10 = 24 cm. Área = (base*altura)/2 = (6*8)/2 = 24 cm².']
                ],
                // U4: Congruencia y semejanza
                4 => [
                    ['texto' => '¿Cuál de los siguientes NO es un criterio estándar de congruencia de triángulos?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'AAA (Ángulo, Ángulo, Ángulo)', 'B' => 'LLL (Lado, Lado, Lado)', 'C' => 'LAL (Lado, Ángulo, Lado)', 'D' => 'ALA (Ángulo, Lado, Ángulo)'], 'correcta' => 'A'],
                    ['texto' => 'Si dos triángulos semejantes tienen una razón de semejanza de 1:3, la razón de sus áreas correspondientes es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1:9', 'B' => '1:3', 'C' => '1:6', 'D' => '1:27'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál de las siguientes condiciones define formalmente la semejanza de dos polígonos?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Ángulos correspondientes congruentes y lados homólogos proporcionales', 'B' => 'Mismo número de lados y misma área', 'C' => 'Lados correspondientes de igual longitud', 'D' => 'Tener la misma orientación en el plano'], 'correcta' => 'A'],
                    ['texto' => 'En un triángulo rectángulo, los catetos miden 5 cm y 12 cm. ¿Cuánto mide la hipotenusa?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '13 cm', 'B' => '17 cm', 'C' => '15 cm', 'D' => '20 cm'], 'correcta' => 'A'],
                    ['texto' => 'El Teorema de Tales establece principalmente relaciones de:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Semejanza entre segmentos cortados por paralelas', 'B' => 'Congruencia de triángulos rectángulos', 'C' => 'Relaciones de perímetros en círculos', 'D' => 'Cálculo de áreas en cuadriláteros'], 'correcta' => 'A'],
                    ['texto' => 'Un poste vertical de 6 metros de altura proyecta una sombra de 4 metros. A la misma hora, un árbol proyecta una sombra de 12 metros. ¿Cuál es la altura del árbol?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '18 metros', 'B' => '12 metros', 'C' => '8 metros', 'D' => '24 metros'], 'correcta' => 'A'],
                    ['texto' => 'En un triángulo rectángulo, la hipotenusa mide 10 cm y uno de sus catetos mide 6 cm. ¿Cuánto mide el otro cateto?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '8 cm', 'B' => '4 cm', 'C' => '16 cm', 'D' => '9 cm'], 'correcta' => 'A'],
                    ['texto' => 'Dos figuras geométricas que tienen exactamente la misma forma y el mismo tamaño se consideran:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Congruentes', 'B' => 'Semejantes', 'C' => 'Equivalentes', 'D' => 'Simétricas'], 'correcta' => 'A'],
                    ['texto' => '¿Qué criterio asegura la semejanza de dos triángulos si sólo conocemos las medidas de sus tres lados?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'LLL (Lado, Lado, Lado)', 'B' => 'LAL (Lado, Ángulo, Lado)', 'C' => 'AAA', 'D' => 'ALA'], 'correcta' => 'A'],
                    ['texto' => 'Si un triángulo rectángulo tiene catetos iguales de longitud \\( x \\) y su hipotenusa mide \\( 2\\sqrt{2} \\), ¿cuánto vale \\( x \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '2', 'B' => '4', 'C' => '\\( \\sqrt{2} \\)', 'D' => '8'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la razón de proporcionalidad de sus perímetros si dos triángulos son semejantes con razón de semejanza \\( k = 4 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '4', 'B' => '16', 'C' => '2', 'D' => '8'], 'correcta' => 'A'],
                    ['texto' => 'Si cortamos los lados de un triángulo con una recta paralela a su base, los dos triángulos resultantes son:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Semejantes', 'B' => 'Congruentes', 'C' => 'Equiláteros', 'D' => 'Rectángulos'], 'correcta' => 'A'],
                    ['texto' => '¿Cuánto mide la diagonal de un cuadrado que tiene 5 cm por lado?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 5\\sqrt{2} \\text{ cm} \\)', 'B' => '10 cm', 'C' => '5 cm', 'D' => '\\( \\sqrt{50} \\text{ cm} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Enuncia formalmente el Teorema de Pitágoras y explica brevemente cómo se aplica en la vida cotidiana.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'El teorema establece que en todo triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos (c² = a² + b²). Se usa para calcular distancias inaccesibles como alturas de edificios, pendientes de rampas, etc.'],
                    ['texto' => 'Un triángulo ABC tiene lados AB=6, BC=8 y AC=10. Otro triángulo semejante A\'B\'C\' tiene un perímetro de 48. Encuentra las medidas de sus tres lados.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Perímetro ABC = 24. Razón de semejanza k = Perímetro A\'B\'C\' / Perímetro ABC = 48 / 24 = 2. Los lados homólogos del segundo triángulo miden: A\'B\' = 6*2 = 12, B\'C\' = 8*2 = 16, y A\'C\' = 10*2 = 20.']
                ]
            ],
            // ================== SEMESTRE 3 ==================
            3 => [
                // U1: Trigonometría
                1 => [
                    ['texto' => 'En un triángulo rectángulo, la razón trigonométrica del cateto opuesto entre la hipotenusa se define como:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Seno', 'B' => 'Coseno', 'C' => 'Tangente', 'D' => 'Secante'], 'correcta' => 'A'],
                    ['texto' => 'En un triángulo rectángulo, si el cateto adyacente al ángulo \\( \\theta \\) mide 4 cm y la hipotenusa mide 5 cm, ¿cuánto vale \\( \\cos(\\theta) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0.8', 'B' => '0.6', 'C' => '1.25', 'D' => '0.75'], 'correcta' => 'A'],
                    ['texto' => 'La Ley de Senos establece la relación proporcional de:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{a}{\\sin(A)} = \\frac{b}{\\sin(B)} = \\frac{c}{\\sin(C)} \\)', 'B' => '\\( a^2 = b^2 + c^2 - 2bc\\cos(A) \\)', 'C' => '\\( \\sin(A) + \\cos(A) = 1 \\)', 'D' => '\\( \\sin^2(x) = 1 - \\cos(x) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál de las siguientes relaciones trigonométricas es equivalente a la tangente del ángulo?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{\\sin(\\theta)}{\\cos(\\theta)} \\)', 'B' => '\\( \\frac{\\cos(\\theta)}{\\sin(\\theta)} \\)', 'C' => '\\( \\sin(\\theta)\\cos(\\theta) \\)', 'D' => '\\( \\frac{1}{\\cos(\\theta)} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra el valor del lado \\( a \\) en un triángulo si \\( b = 8 \\), \\( c = 5 \\) y el ángulo comprendido \\( A = 60° \\) (usa la Ley de Cosenos y \\( \\cos(60°) = 0.5 \\)).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '7', 'B' => '9', 'C' => '\\( \\sqrt{59} \\)', 'D' => '6.5'], 'correcta' => 'A'],
                    ['texto' => 'La identidad trigonométrica fundamental pitagórica está dada por la expresión:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\sin^2(\\theta) + \\cos^2(\\theta) = 1 \\)', 'B' => '\\( \\sin(\\theta) + \\cos(\\theta) = 1 \\)', 'C' => '\\( 1 + \\tan^2(\\theta) = \\cos^2(\\theta) \\)', 'D' => '\\( \\sin^2(\\theta) - \\cos^2(\\theta) = 1 \\)'], 'correcta' => 'A'],
                    ['texto' => 'El valor exacto de la función trigonométrica \\( \\sin(30°) \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0.5', 'B' => '\\( \\frac{\\sqrt{3}}{2} \\)', 'C' => '\\( \\frac{\\sqrt{2}}{2} \\)', 'D' => '1'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor exacto de la función trigonométrica \\( \\cos(90°) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0', 'B' => '1', 'C' => '-1', 'D' => '0.5'], 'correcta' => 'A'],
                    ['texto' => 'En un triángulo oblicuángulo, si conocemos dos lados y el ángulo comprendido entre ellos, debemos usar la Ley de:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Cosenos', 'B' => 'Senos', 'C' => 'Pitágoras', 'D' => 'Tangentes'], 'correcta' => 'A'],
                    ['texto' => 'La recíproca o inversa multiplicativa de la función cosecante es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Seno', 'B' => 'Secante', 'C' => 'Coseno', 'D' => 'Tangente'], 'correcta' => 'A'],
                    ['texto' => '¿Para qué ángulo \\( \\theta \\) entre 0° y 90° se cumple que \\( \\sin(\\theta) = \\cos(\\theta) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '45°', 'B' => '30°', 'C' => '60°', 'D' => '90°'], 'correcta' => 'A'],
                    ['texto' => 'Si en un triángulo rectángulo el cateto opuesto es igual al cateto adyacente, ¿cuál es el valor de la tangente?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1', 'B' => '0', 'C' => '0.5', 'D' => 'Infinita'], 'correcta' => 'A'],
                    ['texto' => 'En un triángulo con lados \\( a = 6 \\) y \\( b = 6 \\), si el ángulo \\( A = 45° \\), ¿cuánto vale el ángulo \\( B \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '45°', 'B' => '90°', 'C' => '60°', 'D' => '30°'], 'correcta' => 'A'],
                    ['texto' => 'Explica detalladamente en qué casos de triángulos oblicuángulos se aplica la Ley de Senos y en cuáles la Ley de Cosenos.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'La Ley de Senos se usa cuando conocemos un lado y su ángulo opuesto más otro dato (LAA o LLA). La Ley de Cosenos se aplica cuando conocemos los tres lados (LLL) o dos lados y el ángulo comprendido entre ellos (LAL).'],
                    ['texto' => 'Desde un faro de 40 m de altura, el ángulo de depresión de un barco en el mar es de 30°. ¿A qué distancia horizontal se encuentra el barco del faro?', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Usando tan(30°) = opuesto / adyacente => tan(30°) = 40 / d => d = 40 / tan(30°) = 40 / (1/raíz(3)) = 40*raíz(3) ≈ 69.28 metros.']
                ],
                // U2: Geometría analítica
                2 => [
                    ['texto' => '¿Cuál es la distancia entre los puntos cartesiano \\( A(1, 2) \\) y \\( B(4, 6) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '25', 'C' => '7', 'D' => '\\( \\sqrt{7} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de la recta que pasa por los puntos \\( (2, -1) \\) y \\( (6, 7) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '2', 'B' => '-2', 'C' => '0.5', 'D' => '4'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las coordenadas del punto medio del segmento de línea entre \\( (2, 8) \\) y \\( (8, 2) \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (5, 5) \\)', 'B' => '\\( (3, 3) \\)', 'C' => '\\( (10, 10) \\)', 'D' => '\\( (4, 4) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si los puntos \\( (1, 1) \\), \\( (2, 3) \\) y \\( (3, y) \\) son colineales (están sobre la misma recta), ¿cuánto vale \\( y \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '4', 'C' => '6', 'D' => '3'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de la recta perpendicular al segmento de extremos \\( (0, 0) \\) y \\( (3, 6) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( -\\frac{1}{2} \\)', 'B' => '2', 'C' => '-2', 'D' => '\\( \\frac{1}{2} \\)'], 'correcta' => 'A'],
                    ['texto' => 'El ángulo de inclinación de una recta con pendiente \\( m = 1 \\) es exactamente de:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '45°', 'B' => '90°', 'C' => '30°', 'D' => '60°'], 'correcta' => 'A'],
                    ['texto' => 'La distancia entre el origen \\( (0, 0) \\) y el punto cartesiano \\( (-3, -4) \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '-5', 'C' => '25', 'D' => '\\( \\sqrt{7} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de la recta que pasa por \\( (-2, 5) \\) y \\( (4, 5) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Cero', 'B' => 'Indefinida', 'C' => '5', 'D' => '1'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor del punto medio entre \\( A(-3, -1) \\) y \\( B(5, 7) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (1, 3) \\)', 'B' => '\\( (2, 6) \\)', 'C' => '\\( (1, 4) \\)', 'D' => '\\( (2, 3) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si una recta pasa por el origen y tiene un ángulo de inclinación de 135°, ¿cuál es su pendiente?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-1', 'B' => '1', 'C' => '0', 'D' => 'Indefinida'], 'correcta' => 'A'],
                    ['texto' => '¿Qué cuadrante tiene coordenadas de la forma \\( (x, y) \\) donde \\( x < 0 \\) y \\( y > 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Segundo cuadrante', 'B' => 'Primer cuadrante', 'C' => 'Tercer cuadrante', 'D' => 'Cuarto cuadrante'], 'correcta' => 'A'],
                    ['texto' => 'Calcula la distancia entre los puntos \\( (0, 2) \\) y \\( (0, -6) \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '8', 'B' => '-4', 'C' => '4', 'D' => '6'], 'correcta' => 'A'],
                    ['texto' => 'Si los puntos \\( A(1, 1) \\) y \\( B(4, 5) \\) forman un segmento, ¿cuánto mide dicho segmento?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '25', 'C' => '6', 'D' => '7'], 'correcta' => 'A'],
                    ['texto' => 'Escribe las fórmulas generales para determinar la distancia entre dos puntos y el punto medio en un plano cartesiano bidimensional.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Distancia: d = raíz((x2 - x1)² + (y2 - y1)²). Punto Medio: Pm = ((x1 + x2)/2, (y1 + y2)/2).'],
                    ['texto' => 'Determina si el triángulo con vértices \\( A(1, 1) \\), \\( B(4, 1) \\) y \\( C(1, 5) \\) es rectángulo aplicando el Teorema de Pitágoras con las distancias de sus lados.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Distancias: AB = raíz((4-1)² + 0) = 3. AC = raíz(0 + (5-1)²) = 4. BC = raíz((1-4)² + (5-1)²) = raíz(9+16) = 5. Como AB² + AC² = 3² + 4² = 9 + 16 = 25 = BC² = 5², sí es un triángulo rectángulo con hipotenusa BC.']
                ],
                // U3: La recta
                3 => [
                    ['texto' => 'La ecuación ordinaria de una recta que pasa por \\( (0, 4) \\) y tiene pendiente \\( m = -3 \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = -3x + 4 \\)', 'B' => '\\( y = -3x - 4 \\)', 'C' => '\\( y = 4x - 3 \\)', 'D' => '\\( y = 3x + 4 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Expresa la ecuación general de la recta \\( y = 2x - 3 \\) en la forma \\( Ax + By + C = 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 2x - y - 3 = 0 \\)', 'B' => '\\( 2x + y - 3 = 0 \\)', 'C' => '\\( 2x - y + 3 = 0 \\)', 'D' => '\\( -2x + y - 3 = 0 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de la recta con ecuación general \\( 3x + 2y - 6 = 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( -\\frac{3}{2} \\)', 'B' => '\\( \\frac{3}{2} \\)', 'C' => '\\( -3 \\)', 'D' => '3'], 'correcta' => 'A'],
                    ['texto' => 'Dos rectas con ecuaciones \\( y = m1x + b1 \\) y \\( y = m2x + b2 \\) son perpendiculares si y sólo si:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( m1 \\cdot m2 = -1 \\)', 'B' => '\\( m1 = m2 \\)', 'C' => '\\( m1 + m2 = 0 \\)', 'D' => '\\( m1 \\cdot m2 = 1 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la ecuación punto-pendiente de la recta que pasa por \\( (-1, 5) \\) con pendiente \\( m = 4 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y - 5 = 4(x + 1) \\)', 'B' => '\\( y + 5 = 4(x - 1) \\)', 'C' => '\\( y - 5 = 4(x - 1) \\)', 'D' => '\\( y - 1 = 4(x - 5) \\)'], 'correcta' => 'A'],
                    ['texto' => 'Dada la ecuación de la recta \\( 4x - 5y + 20 = 0 \\), su intersección con el eje Y es el punto:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (0, 4) \\)', 'B' => '\\( (0, -4) \\)', 'C' => '\\( (-5, 0) \\)', 'D' => '\\( (0, 5) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la pendiente de la recta paralela a la recta \\( 2x - 3y + 6 = 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{2}{3} \\)', 'B' => '\\( -\\frac{2}{3} \\)', 'C' => '\\( 2 \\)', 'D' => '\\( -3 \\)'], 'correcta' => 'A'],
                    ['texto' => 'La ecuación general de una recta horizontal que pasa por el punto \\( (3, -2) \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y + 2 = 0 \\)', 'B' => '\\( x - 3 = 0 \\)', 'C' => '\\( y - 2 = 0 \\)', 'D' => '\\( y = 3 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál de las siguientes representa la ecuación simétrica o canónica de la recta?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{x}{a} + \\frac{y}{b} = 1 \\)', 'B' => '\\( Ax + By + C = 0 \\)', 'C' => '\\( y - y1 = m(x - x1) \\)', 'D' => '\\( y = mx + b \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la distancia del origen \\( (0, 0) \\) a la recta \\( 3x - 4y + 10 = 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '2', 'B' => '10', 'C' => '5', 'D' => '2.5'], 'correcta' => 'A'],
                    ['texto' => 'La ecuación general de la recta que pasa por los puntos \\( (0, 3) \\) y \\( (2, 0) \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 3x + 2y - 6 = 0 \\)', 'B' => '\\( 2x + 3y - 6 = 0 \\)', 'C' => '\\( 3x - 2y + 6 = 0 \\)', 'D' => '\\( 2x - 3y + 6 = 0 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de la pendiente de la recta \\( y = 7 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0', 'B' => '7', 'C' => 'Indefinido', 'D' => '1'], 'correcta' => 'A'],
                    ['texto' => 'Determina si las rectas \\( 2x - y + 4 = 0 \\) y \\( x + 2y - 6 = 0 \\) son paralelas, perpendiculares u oblicuas.', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Perpendiculares', 'B' => 'Paralelas', 'C' => 'Oblicuas', 'D' => 'Coincidentes'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra la ecuación general de la recta que pasa por los puntos \\( A(1, 2) \\) y \\( B(3, 8) \\) detallando paso a paso tu deducción.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Pendiente: m = (8-2)/(3-1) = 6/2 = 3. Punto-pendiente con A(1,2): y - 2 = 3(x - 1) => y - 2 = 3x - 3 => Ecuación general: 3x - y - 1 = 0.'],
                    ['texto' => 'Calcula la distancia del punto \\( P(3, 4) \\) a la línea recta cuya ecuación general está dada por \\( 5x + 12y - 12 = 0 \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Usando la fórmula d = |Ax0 + By0 + C| / raíz(A² + B²): d = |5(3) + 12(4) - 12| / raíz(5² + 12²) = |15 + 48 - 12| / raíz(25 + 144) = |51| / 13 ≈ 3.92.']
                ],
                // U4: Parábola
                4 => [
                    ['texto' => '¿Cuál es el vértice de la parábola con ecuación ordinaria \\( (x - 2)^2 = 8(y - 3) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (2, 3) \\)', 'B' => '\\( (-2, -3) \\)', 'C' => '\\( (3, 2) \\)', 'D' => '\\( (8, 2) \\)'], 'correcta' => 'A'],
                    ['texto' => 'En la ecuación de la parábola vertical con vértice en el origen \\( x^2 = 4py \\), si \\( p > 0 \\), la parábola abre hacia:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Arriba', 'B' => 'Abajo', 'C' => 'La derecha', 'D' => 'La izquierda'], 'correcta' => 'A'],
                    ['texto' => 'La directriz de la parábola con ecuación \\( x^2 = -12y \\) está dada por la recta:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = 3 \\)', 'B' => '\\( y = -3 \\)', 'C' => '\\( x = 3 \\)', 'D' => '\\( x = -3 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la longitud del lado recto (LR) de la parábola con ecuación \\( (y + 1)^2 = -16(x - 5) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '16', 'B' => '4', 'C' => '8', 'D' => '-16'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la ecuación de la parábola con vértice en el origen \\( (0, 0) \\) y foco en el punto \\( (3, 0) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y^2 = 12x \\)', 'B' => '\\( x^2 = 12y \\)', 'C' => '\\( y^2 = -12x \\)', 'D' => '\\( y^2 = 3x \\)'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las coordenadas del foco de la parábola vertical con ecuación \\( (x - 1)^2 = 4(y - 2) \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (1, 3) \\)', 'B' => '\\( (1, 2) \\)', 'C' => '\\( (2, 2) \\)', 'D' => '\\( (1, 1) \\)'], 'correcta' => 'A'],
                    ['texto' => 'La ecuación general de una parábola horizontal es de la forma:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y^2 + Dx + Ey + F = 0 \\)', 'B' => '\\( x^2 + Dx + Ey + F = 0 \\)', 'C' => '\\( x^2 + y^2 + Dx + Ey + F = 0 \\)', 'D' => '\\( Ax + By + C = 0 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la distancia focal \\( p \\) de la parábola con ecuación \\( y^2 = 24x \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '6', 'B' => '24', 'C' => '12', 'D' => '4'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra la ecuación de la directriz de la parábola horizontal con foco en \\( (2, 0) \\) y vértice en \\( (0, 0) \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = -2 \\)', 'B' => '\\( x = 2 \\)', 'C' => '\\( y = -2 \\)', 'D' => '\\( y = 2 \\)'], 'correcta' => 'A'],
                    ['texto' => 'La definición de la parábola como lugar geométrico establece la igualdad de distancias entre:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Un punto de la curva al foco y a la directriz', 'B' => 'Dos puntos fijos llamados focos', 'C' => 'El vértice al centro del plano', 'D' => 'Los extremos del lado recto'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el foco de la parábola horizontal con ecuación \\( (y - 4)^2 = -8(x - 2) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (0, 4) \\)', 'B' => '\\( (2, 4) \\)', 'C' => '\\( (4, 4) \\)', 'D' => '\\( (2, 2) \\)'], 'correcta' => 'A'],
                    ['texto' => 'La longitud del lado recto de cualquier parábola con parámetro \\( p \\) se calcula mediante la fórmula:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 4|p| \\)', 'B' => '\\( 2|p| \\)', 'C' => '\\( p^2 \\)', 'D' => '\\( \\frac{p}{2} \\)'], 'correcta' => 'A'],
                    ['texto' => 'Si el foco de una parábola es \\( (0, -2) \\) y su directriz es \\( y = 2 \\), su ecuación ordinaria es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x^2 = -8y \\)', 'B' => '\\( y^2 = -8x \\)', 'C' => '\\( x^2 = 8y \\)', 'D' => '\\( x^2 = -2y \\)'], 'correcta' => 'A'],
                    ['texto' => 'Dada la ecuación de la parábola \\( y^2 - 4y - 8x + 12 = 0 \\), encuentra su vértice y foco completando el trinomio cuadrado perfecto.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'y^2 - 4y = 8x - 12 => (y-2)^2 - 4 = 8x - 12 => (y-2)^2 = 8x - 8 => (y-2)^2 = 8(x-1). Vértice V(1, 2). Parámetro 4p=8 => p=2. Foco F(1+2, 2) = F(3, 2).'],
                    ['texto' => 'Determina la ecuación general de la parábola con vértice en \\( (3, 2) \\) y foco en \\( (3, 4) \\). Muestra tu procedimiento.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Vértice V(3,2) y Foco F(3,4). Es vertical (abre hacia arriba), con p = 4 - 2 = 2. Ecuación: (x - h)^2 = 4p(y - k) => (x - 3)^2 = 8(y - 2) => x^2 - 6x + 9 = 8y - 16 => x^2 - 6x - 8y + 25 = 0.']
                ],
                // U5: Circunferencia y Elipse
                5 => [
                    ['texto' => '¿Cuál es el centro de la circunferencia con ecuación ordinaria \\( (x - 5)^2 + (y + 3)^2 = 16 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (5, -3) \\)', 'B' => '\\( (-5, 3) \\)', 'C' => '\\( (5, 3) \\)', 'D' => '\\( (16, 5) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el radio de la circunferencia representada por la ecuación \\( x^2 + y^2 = 49 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '7', 'B' => '49', 'C' => '9.8', 'D' => '14'], 'correcta' => 'A'],
                    ['texto' => 'La ecuación general de una circunferencia con centro en el origen es siempre de la forma:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x^2 + y^2 - r^2 = 0 \\)', 'B' => '\\( x^2 - y^2 = r^2 \\)', 'C' => '\\( (x-h)^2 + (y-k)^2 = r^2 \\)', 'D' => '\\( Ax^2 + By^2 + C = 0 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Dada la ecuación de la elipse horizontal \\( \\frac{x^2}{25} + \\frac{y^2}{9} = 1 \\), la longitud de su semieje mayor \\( a \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '25', 'C' => '3', 'D' => '9'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la ecuación ordinaria de una elipse vertical con centro en el origen?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{x^2}{b^2} + \\frac{y^2}{a^2} = 1 \\)', 'B' => '\\( \\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1 \\)', 'C' => '\\( \\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1 \\)', 'D' => '\\( x^2 + y^2 = a^2 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las coordenadas de los focos de la elipse horizontal con ecuación \\( \\frac{x^2}{25} + \\frac{y^2}{16} = 1 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (3, 0) \\) y \\( (-3, 0) \\)', 'B' => '\\( (5, 0) \\) y \\( (-5, 0) \\)', 'C' => '\\( (4, 0) \\) y \\( (-4, 0) \\)', 'D' => '\\( (9, 0) \\) y \\( (-9, 0) \\)'], 'correcta' => 'A'],
                    ['texto' => 'La excentricidad \\( e \\) de una elipse mide su achatamiento y se calcula mediante la fórmula:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( e = \\frac{c}{a} \\)', 'B' => '\\( e = \\frac{a}{c} \\)', 'C' => '\\( e = \\sqrt{a^2 - b^2} \\)', 'D' => '\\( e = c \\cdot a \\)'], 'correcta' => 'A'],
                    ['texto' => 'Dada la ecuación general de la circunferencia \\( x^2 + y^2 - 4x + 6y - 12 = 0 \\), ¿cuánto vale su radio?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '25', 'C' => '\\( \\sqrt{12} \\)', 'D' => '6'], 'correcta' => 'A'],
                    ['texto' => 'Si el centro de una elipse está en \\( (h, k) \\), su ecuación horizontal ordinaria es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{(x-h)^2}{a^2} + \\frac{(y-k)^2}{b^2} = 1 \\)', 'B' => '\\( \\frac{(x-h)^2}{b^2} + \\frac{(y-k)^2}{a^2} = 1 \\)', 'C' => '\\( \\frac{(x+h)^2}{a^2} + \\frac{(y+k)^2}{b^2} = 1 \\)', 'D' => '\\( (x-h)^2 + (y-k)^2 = 1 \\)'], 'correcta' => 'A'],
                    ['texto' => 'La relación pitagórica para los semiejes de una elipse con semieje mayor \\( a \\), menor \\( b \\) y distancia focal \\( c \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( a^2 = b^2 + c^2 \\)', 'B' => '\\( b^2 = a^2 + c^2 \\)', 'C' => '\\( c^2 = a^2 + b^2 \\)', 'D' => '\\( a^2 + b^2 + c^2 = 1 \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál de las siguientes representa el lugar geométrico cuyos puntos sumados desde dos focos fijos siempre da una constante \\( 2a \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Elipse', 'B' => 'Circunferencia', 'C' => 'Parábola', 'D' => 'Hipérbola'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra el centro y radio de la circunferencia: \\( x^2 + y^2 + 10x - 8y + 40 = 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Centro (-5, 4), Radio = 1', 'B' => 'Centro (5, -4), Radio = 1', 'C' => 'Centro (-5, 4), Radio = 2', 'D' => 'Centro (5, -4), Radio = 4'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la longitud del eje mayor de la elipse con ecuación \\( \\frac{x^2}{100} + \\frac{y^2}{64} = 1 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '20', 'B' => '10', 'C' => '16', 'D' => '100'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las coordenadas de los vértices y focos de la elipse: \\( 9x^2 + 25y^2 = 225 \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Dividiendo entre 225: x²/25 + y²/9 = 1. Es horizontal con a=5, b=3. c = raíz(25-9) = 4. Vértices: (+/-5, 0). Focos: (+/-4, 0).'],
                    ['texto' => 'Deduce la ecuación general de la circunferencia que tiene su centro en el punto \\( C(2, -3) \\) y es tangente al eje X.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Como es tangente al eje X, el radio r es igual a la distancia vertical del centro al eje X, es decir, r = |-3| = 3. Ecuación ordinaria: (x-2)^2 + (y+3)^2 = 9 => x^2 - 4x + 4 + y^2 + 6y + 9 = 9 => Ecuación general: x^2 + y^2 - 4x + 6y + 4 = 0.']
                ]
            ],
            // ================== SEMESTRE 4 ==================
            4 => [
                // U1: Funciones polinomiales
                1 => [
                    ['texto' => 'El dominio de cualquier función polinomial real de grado impar o par es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Todos los números reales', 'B' => 'Reales positivos', 'C' => 'Reales diferentes de cero', 'D' => 'Reales mayores o iguales a cero'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el residuo obtenido al dividir el polinomio \\( P(x) = x^3 - 4x^2 + 5x - 2 \\) entre \\( x - 2 \\) usando el Teorema del Residuo?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0', 'B' => '4', 'C' => '2', 'D' => '-2'], 'correcta' => 'A'],
                    ['texto' => 'Según el Teorema del Factor, \\( x - c \\) es un factor del polinomio \\( P(x) \\) si y sólo si:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( P(c) = 0 \\)', 'B' => '\\( P(c) = 1 \\)', 'C' => '\\( P(-c) = 0 \\)', 'D' => '\\( P(0) = c \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el grado del polinomio resultante de multiplicar \\( (x^2 - 3)(x^3 + 2x) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '6', 'C' => '4', 'D' => '2'], 'correcta' => 'A'],
                    ['texto' => 'Si un polinomio de grado 3 tiene raíces reales en \\( x = 1 \\), \\( x = -2 \\) y \\( x = 3 \\), su ecuación factorizada es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = (x - 1)(x + 2)(x - 3) \\)', 'B' => '\\( y = (x + 1)(x - 2)(x + 3) \\)', 'C' => '\\( y = (x - 1)(x - 2)(x - 3) \\)', 'D' => '\\( y = x(x-1)(x+2) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el comportamiento en el infinito de la función polinomial \\( y = -x^4 + 3x^2 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Tiende a menos infinito en ambos extremos', 'B' => 'Tiende a más infinito en ambos extremos', 'C' => 'Sube a la derecha y baja a la izquierda', 'D' => 'Baja a la derecha y sube a la izquierda'], 'correcta' => 'A'],
                    ['texto' => 'Encuentra las raíces del polinomio cuadrático: \\( P(x) = x^2 - 7x + 12 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '3 y 4', 'B' => '-3 y -4', 'C' => '2 y 6', 'D' => '1 y 12'], 'correcta' => 'A'],
                    ['texto' => '¿Cuántas raíces reales o complejas tiene exactamente un polinomio de grado \\( n \\) según el Teorema Fundamental del Álgebra?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( n \\) raíces', 'B' => '\\( n - 1 \\) raíces', 'C' => '\\( 2n \\) raíces', 'D' => 'Al menos una raíz real'], 'correcta' => 'A'],
                    ['texto' => 'El valor de la función polinomial \\( P(x) = 2x^3 - x^2 + 5 \\) cuando \\( x = -1 \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '2', 'B' => '4', 'C' => '6', 'D' => '8'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el residuo al dividir \\( x^4 - 1 \\) entre \\( x - 1 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0', 'B' => '1', 'C' => '-1', 'D' => '2'], 'correcta' => 'A'],
                    ['texto' => 'Si \\( P(x) = x^3 - x^2 - x + 1 \\), una de sus raíces es \\( x = 1 \\). Factoriza completamente el polinomio.', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (x-1)^2(x+1) \\)', 'B' => '\\( (x-1)(x+1)^2 \\)', 'C' => '\\( (x-1)(x-2)(x+1) \\)', 'D' => '\\( x(x-1)^2 \\)'], 'correcta' => 'A'],
                    ['texto' => 'El coeficiente principal del polinomio \\( P(x) = 5x^2 - 4x^3 + 2x - 1 \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-4', 'B' => '5', 'C' => '2', 'D' => '-1'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la ordenada al origen de la función polinomial \\( y = 3(x-1)(x+2)(x-3) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '18', 'B' => '-18', 'C' => '6', 'D' => '9'], 'correcta' => 'A'],
                    ['texto' => 'Explica con tus palabras en qué consisten y cómo se relacionan el Teorema del Residuo y el Teorema del Factor.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'El Teorema del Residuo dice que al dividir P(x) entre x-c, el residuo es P(c). El Teorema del Factor dice que si el residuo P(c) es cero, entonces x-c es un divisor exacto (un factor) de P(x).'],
                    ['texto' => 'Encuentra todas las raíces del polinomio \\( P(x) = x^3 - 6x^2 + 11x - 6 \\) empleando división sintética.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Probando raíz x=1: P(1)=1-6+11-6=0. Dividiendo sintéticamente entre 1 queda x²-5x+6. Factorizando x²-5x+6 = (x-2)(x-3). Las raíces son x = 1, x = 2 y x = 3.']
                ],
                // U2: Racionales y radicales
                2 => [
                    ['texto' => '¿Cuál es el dominio de la función racional \\( f(x) = \\frac{2x - 1}{x - 3} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Todos los reales excepto x = 3', 'B' => 'Todos los reales excepto x = 0.5', 'C' => 'Todos los reales mayores a 3', 'D' => 'Todos los reales'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la ecuación de la asíntota vertical de la función \\( f(x) = \\frac{5}{x + 4} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = -4 \\)', 'B' => '\\( x = 4 \\)', 'C' => '\\( y = 0 \\)', 'D' => '\\( y = -4 \\)'], 'correcta' => 'A'],
                    ['texto' => 'Para la función racional \\( f(x) = \\frac{3x^2 - 5}{x^2 - 1} \\), ¿cuál es su asíntota horizontal?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = 3 \\)', 'B' => '\\( y = 1 \\)', 'C' => '\\( y = 0 \\)', 'D' => 'No tiene asíntota horizontal'], 'correcta' => 'A'],
                    ['texto' => 'El dominio de la función con radical \\( f(x) = \\sqrt{x - 5} \\) en los números reales es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( [5, \\infty) \\)', 'B' => '\\( (5, \\infty) \\)', 'C' => '\\( (-\\infty, 5] \\)', 'D' => 'Todos los reales'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la asíntota horizontal de la función racional \\( f(x) = \\frac{4x - 2}{2x + 8} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = 2 \\)', 'B' => '\\( y = -4 \\)', 'C' => '\\( y = 4 \\)', 'D' => '\\( y = 0 \\)'], 'correcta' => 'A'],
                    ['texto' => 'El dominio de la función con radical de grado impar \\( f(x) = \\sqrt[3]{x - 2} \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Todos los números reales', 'B' => '\\( [2, \\infty) \\)', 'C' => '\\( (2, \\infty) \\)', 'D' => 'Reales positivos únicamente'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál de las siguientes condiciones describe una asíntota vertical en una función racional simplificada \\( f(x) = \\frac{P(x)}{Q(x)} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Los valores de x que hacen cero al denominador Q(x)', 'B' => 'La división de los coeficientes principales de P(x) y Q(x)', 'C' => 'Las raíces del numerador P(x)', 'D' => 'Los valores donde x tiende a infinito'], 'correcta' => 'A'],
                    ['texto' => '¿Qué ocurre con la gráfica de \\( f(x) = \\frac{x^2 - 4}{x - 2} \\) en el valor \\( x = 2 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Hay una discontinuidad evitable (un hueco)', 'B' => 'Hay una asíntota vertical', 'C' => 'Hay una asíntota horizontal', 'D' => 'La función es continua en ese punto'], 'correcta' => 'A'],
                    ['texto' => 'El dominio de la función con radical \\( y = \\sqrt{9 - x^2} \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( [-3, 3] \\)', 'B' => '\\( (-\\infty, -3] \\cup [3, \\infty) \\)', 'C' => '\\( [0, 3] \\)', 'D' => 'Todos los reales'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la asíntota horizontal de la función \\( f(x) = \\frac{2}{x^2 + 1} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( y = 0 \\)', 'B' => '\\( y = 2 \\)', 'C' => '\\( y = 1 \\)', 'D' => 'No tiene asíntota'], 'correcta' => 'A'],
                    ['texto' => 'El rango o contradominio de la función con radical básica \\( y = \\sqrt{x} \\) es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( [0, \\infty) \\)', 'B' => 'Todos los reales', 'C' => '\\( (0, \\infty) \\)', 'D' => '\\( [0, 1] \\)'], 'correcta' => 'A'],
                    ['texto' => 'Calcula la coordenada del punto de intersección con el eje Y de la función racional \\( f(x) = \\frac{3x - 6}{x + 2} \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (0, -3) \\)', 'B' => '\\( (2, 0) \\)', 'C' => '\\( (0, 3) \\)', 'D' => '\\( (0, -6) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la asíntota vertical de la función \\( y = \\frac{x^2}{x^2 - 9} \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( x = 3 \\) y \\( x = -3 \\)', 'B' => '\\( x = 9 \\)', 'C' => '\\( y = 1 \\)', 'D' => 'No tiene asíntotas verticales'], 'correcta' => 'A'],
                    ['texto' => 'Define qué es una asíntota vertical y una asíntota horizontal y explica cómo se calculan analíticamente.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Una asíntota vertical es una recta x = c donde la función tiende al infinito; se calcula hallando los valores que hacen cero el denominador tras simplificar. La horizontal y = k describe el comportamiento al infinito; se halla analizando el límite cuando x tiende a infinito.'],
                    ['texto' => 'Encuentra detalladamente el dominio de la función con radical \\( f(x) = \\sqrt{2x - 8} \\) y describe cómo graficarla a grandes rasgos.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Para que el radical sea real, el radicando debe ser mayor o igual a cero: 2x - 8 >= 0 => 2x >= 8 => x >= 4. Dominio: [4, infinito). La gráfica inicia en (4,0) y sube con curvatura cóncava hacia abajo hacia la derecha.']
                ],
                // U3: Exponenciales y logarítmicas
                3 => [
                    ['texto' => '¿Cuál es el valor del logaritmo base 10 de 1000? Es decir, \\( \\log_{10}(1000) \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '3', 'B' => '10', 'C' => '2', 'D' => '100'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor del logaritmo de la base? Es decir, \\( \\log_b(b) \\) para cualquier base \\( b > 0 \\).', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1', 'B' => '0', 'C' => '\\( b \\)', 'D' => 'Indefinido'], 'correcta' => 'A'],
                    ['texto' => 'La propiedad del logaritmo de un producto establece que \\( \\log_b(xy) \\) es equivalente a:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\log_b(x) + \\log_b(y) \\)', 'B' => '\\( \\log_b(x) \\cdot \\log_b(y) \\)', 'C' => '\\( \\log_b(x) - \\log_b(y) \\)', 'D' => '\\( y\\log_b(x) \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de \\( x \\) en la ecuación exponencial \\( 2^x = 32 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '4', 'C' => '6', 'D' => '16'], 'correcta' => 'A'],
                    ['texto' => 'La propiedad del logaritmo de una potencia establece que \\( \\log_b(x^k) \\) equivale a:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( k \\cdot \\log_b(x) \\)', 'B' => '\\( \\log_b(x) + k \\)', 'C' => '\\( \\log_b(k \\cdot x) \\)', 'D' => '\\( \\log_b(x)^k \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la función inversa de la función exponencial con base e \\( f(x) = e^x \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'El logaritmo natural \\( \\ln(x) \\)', 'B' => 'El logaritmo común \\( \\log_{10}(x) \\)', 'C' => '\\( x^e \\)', 'D' => '\\( \\frac{1}{e^x} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de \\( x \\) en: \\( \\log_3(x) = 2 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '9', 'B' => '6', 'C' => '8', 'D' => '5'], 'correcta' => 'A'],
                    ['texto' => 'Si una población bacteriana inicial de 100 células se duplica cada hora, ¿qué ecuación representa el número de bacterias \\( P \\) en \\( t \\) horas?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( P = 100 \\cdot 2^t \\)', 'B' => '\\( P = 100 \\cdot t^2 \\)', 'C' => '\\( P = 200t \\)', 'D' => '\\( P = 100 + 2^t \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de \\( \\log_b(1) \\) para cualquier base de logaritmo \\( b > 0 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '0', 'B' => '1', 'C' => '\\( b \\)', 'D' => 'Indefinido'], 'correcta' => 'A'],
                    ['texto' => 'La propiedad de cambio de base para logaritmos permite expresar \\( \\log_a(x) \\) como:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{\\log_b(x)}{\\log_b(a)} \\)', 'B' => '\\( \\log_b(x) - \\log_b(a) \\)', 'C' => '\\( \\log_b(x) \\cdot \\log_b(a) \\)', 'D' => '\\( \\frac{\\log_b(a)}{\\log_b(x)} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de \\( x \\) en: \\( 5^{x-1} = 25 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '3', 'B' => '2', 'C' => '4', 'D' => '5'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el dominio de la función logarítmica básica \\( f(x) = \\log_{10}(x) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( (0, \\infty) \\)', 'B' => 'Todos los reales', 'C' => '\\( [0, \\infty) \\)', 'D' => 'Reales positivos y negativos'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de \\( \\ln(e^4) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '4', 'B' => 'e', 'C' => '1', 'D' => '12'], 'correcta' => 'A'],
                    ['texto' => 'Resuelve la ecuación logarítmica mostrando el desarrollo paso a paso: \\( \\log_2(x) + \\log_2(x-2) = 3 \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Propiedad del producto: log2(x*(x-2)) = 3 => x(x-2) = 2^3 => x² - 2x = 8 => x² - 2x - 8 = 0 => (x-4)(x+2) = 0. Como el argumento del logaritmo debe ser positivo, la única solución real es x = 4.'],
                    ['texto' => 'Una sustancia radiactiva se desintegra según el modelo exponencial \\( N(t) = N_0 \\cdot e^{-0.05t} \\), donde \\( t \\) está en años. Si inicialmente hay 200 gramos, calcula cuánto queda después de 20 años en términos de e.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'N0 = 200. N(20) = 200 * e^(-0.05 * 20) = 200 * e^(-1) = 200 / e gramos ≈ 73.57 gramos.']
                ],
                // U4: Funciones trigonométricas
                4 => [
                    ['texto' => '¿A cuántos grados sexagesimales equivale un ángulo central de \\( \\pi \\) radianes?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '180°', 'B' => '360°', 'C' => '90°', 'D' => '270°'], 'correcta' => 'A'],
                    ['texto' => 'En el círculo unitario, la coordenada \\( y \\) del punto asociado a un ángulo central \\( \\theta \\) representa:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'El Seno del ángulo', 'B' => 'El Coseno del ángulo', 'C' => 'La Tangente del ángulo', 'D' => 'La Secante del ángulo'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor de la función trigonométrica \\( \\sin(\\frac{\\pi}{2}) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '1', 'B' => '0', 'C' => '-1', 'D' => '0.5'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el periodo fundamental de las funciones trigonométricas seno y coseno?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( 2\\pi \\) radianes', 'B' => '\\( \\pi \\) radianes', 'C' => '\\( \\frac{\\pi}{2} \\) radianes', 'D' => '4pi radianes'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el periodo fundamental de la función trigonométrica tangente?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\pi \\) radianes', 'B' => '\\( 2\\pi \\) radianes', 'C' => '\\( \\frac{\\pi}{2} \\) radianes', 'D' => 'Periodo infinito'], 'correcta' => 'A'],
                    ['texto' => 'En el círculo unitario, ¿en qué cuadrante son negativas tanto la función Seno como la función Coseno?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Tercer cuadrante', 'B' => 'Primer cuadrante', 'C' => 'Segundo cuadrante', 'D' => 'Cuarto cuadrante'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el rango o contradominio de la función trigonométrica básica \\( y = \\cos(x) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( [-1, 1] \\)', 'B' => 'Todos los reales', 'C' => '\\( (0, \\infty) \\)', 'D' => '\\( [0, 1] \\)'], 'correcta' => 'A'],
                    ['texto' => '¿A cuántos radianes equivale un ángulo de 90°?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '\\( \\frac{\\pi}{2} \\)', 'B' => '\\( \\pi \\)', 'C' => '\\( 2\\pi \\)', 'D' => '\\( \\frac{\\pi}{4} \\)'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es el valor máximo que puede tomar la función trigonométrica \\( y = 3\\sin(2x) + 1 \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '4', 'B' => '3', 'C' => '2', 'D' => '1'], 'correcta' => 'A'],
                    ['texto' => 'La gráfica de la función tangente tiene asíntotas verticales en los puntos:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => 'Múltiplos impares de \\( \\frac{\\pi}{2} \\)', 'B' => 'Múltiplos enteros de \\( \\pi \\)', 'C' => 'Múltiplos enteros de \\( 2\\pi \\)', 'D' => 'No tiene asíntotas'], 'correcta' => 'A'],
                    ['texto' => 'El valor de la función trigonométrica \\( \\cos(\\pi) \\) en el círculo unitario es:', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '-1', 'B' => '1', 'C' => '0', 'D' => 'Indefinido'], 'correcta' => 'A'],
                    ['texto' => '¿Cuál es la amplitud de la función trigonométrica oscilatoria \\( y = -5\\cos(x) \\)?', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '5', 'B' => '-5', 'C' => '1', 'D' => '2.5'], 'correcta' => 'A'],
                    ['texto' => 'Convierte \\( \\frac{2\\pi}{3} \\) radianes a grados sexagesimales.', 'tipo' => 'opcion_multiple', 'opciones' => ['A' => '120°', 'B' => '150°', 'C' => '60°', 'D' => '135°'], 'correcta' => 'A'],
                    ['texto' => 'Explica la relación entre la medición de ángulos en grados y radianes, deduciendo el factor de conversión correspondiente.', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Una vuelta completa del círculo equivale a 360° sexagesimales o a 2*pi radianes. Por tanto, 180° = pi radianes. El factor de conversión de grados a radianes es pi/180°, y de radianes a grados es 180°/pi.'],
                    ['texto' => 'Determina el periodo, la amplitud y el desplazamiento de fase de la función: \\( y = 2\\sin(3x - \\pi) \\).', 'tipo' => 'respuesta_abierta', 'opciones' => null, 'correcta' => 'Amplitud = |A| = 2. Frecuencia angular B = 3 => Periodo = 2*pi / B = 2*pi / 3. Desplazamiento de fase = C / B = pi / 3 hacia la derecha.']
                ]
            ]
        ];

        // Insertar en la BD
        foreach ($adicionales as $semestreNumero => $unidadesData) {
            $semestre = $semestres->get($semestreNumero);
            if (!$semestre) {
                continue;
            }

            $unidades = Unidad::where('semestre_id', $semestre->id)->get()->keyBy('numero');

            foreach ($unidadesData as $unidadNumero => $preguntasList) {
                $unidad = $unidades->get($unidadNumero);
                if (!$unidad) {
                    continue;
                }

                // Insertar cada pregunta adicional sin eliminar las existentes
                foreach ($preguntasList as $pData) {
                    // Validar si la pregunta ya existe por su texto para evitar duplicidad si el seeder se corre dos veces
                    $exists = Pregunta::where('unidad_id', $unidad->id)
                        ->where('texto_pregunta', $pData['texto'])
                        ->exists();

                    if (!$exists) {
                        Pregunta::create([
                            'unidad_id' => $unidad->id,
                            'texto_pregunta' => $pData['texto'],
                            'tipo_pregunta' => $pData['tipo'],
                            'opciones_json' => $pData['opciones'],
                            'respuesta_correcta' => $pData['correcta']
                        ]);
                    }
                }
            }
        }
    }
}
